### ISSUE TITLE
Capture image - Tools - Limitations

### ISSUE THREAD

**Issue by riverdiego** [Ginj-capture/Ginj#11]
It's an amazing tool, i really appreciate that you provide/share us this tool :) 
After use the tool bar i have the following suggestions:
1- User is not able to draw from the right to left - using Frame, Text or Highlight
![image](https://user-images.githubusercontent.com/22159796/88119590-5254a280-cb97-11ea-9d01-9c0b0c810fc8.png)
Actual: It's stuck and it's only displayed a point, if you use the tool, drawing from the left to right, then it's properly displayed the draw
2- User is not able to remove a Text object using the Delete key
![image](https://user-images.githubusercontent.com/22159796/88119739-b11a1c00-cb97-11ea-90b6-dbcf7b1f4bf6.png)
Actual: It's displayed active (it displays the cursor) once the user clicks on the Text object frame, i guess it should be displayed as an object in order to allow that, only displays the cursor if the user clicks on into the Text object
3- Text Object remains active
![image](https://user-images.githubusercontent.com/22159796/88119966-461d1500-cb98-11ea-8fd3-59c6edf1fc8d.png)
Actual: The text object keeps displaying the cursor even when i've changed to the tool (to Frame) and i've just pasted some frames (see the corners of the last frame) so both components are active. Since this behavior, then i select any frame, i'm unable to remove it with the Delete key (workaround: use the undo key)

**Comment by vicnevicne** [comment]
Thanks for the detailed report.
Dragging right to left : +1 . I didn't think of it while coding (and it was tricky to code handles), and as soon as I started to use Ginj "for real work", it annoyed me immediately. That's indeed more a limitation than a bug, but I should work on it.
Text overlay and focus: indeed, it seems buggy. It's a tricky component because it's the combination of a rectangle and a text area. I have to find out how to accurately deselect the text area when another component is selected. In particular for point (2), can you confirm that even if you click on the border of the rectangle, you are still not able to use the delete key ? Thanks.

**Comment by vicnevicne** [comment]
Both issues are fixed in the code. Will be in the next release.

**Comment by vicnevicne** [comment]
Should be OK in v0.3.7.
I'm closing this. Feel free to update and reopen with details if issue is not fixed for you
