### ISSUE TITLE
maximize History window

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#12]
Feature request:  Is it possible to _maximize_ the history window and even better, change the size (or select different sizes like win10 does under view-small medium large etc) of the preview pictures. 
When searching for taken pictures in history it was previously in Jing a problem to see the picture in a decent size. I think this feature makes it even better ;)

**Comment by vicnevicne** [comment]
Resizing the history window is [in the plans](https://github.com/Ginj-capture/Ginj/blob/b8d5b0ef35d445fe5d732fea895b2ba9444278f9/src/main/java/info/ginj/ui/HistoryFrame.java#L172) indeed, as it was a feature of Jing.
Changing the size of captures, on the other hand, is not trivial because when you click on a capture, you're getting a yellow background and buttons, and these are not easy to adjust. 
That's the drawback of having such a customized look-and-feel : implementing a feature means spending 5 more times in UI tuning... 
So I'm afraid unless someone steps in to help, variable capture size is not on the top-priority list.

**Comment by vicnevicne** [comment]
History window resizing is implemented in v0.4.9
I'm closing this issue, but if you think resizing preview "cells" is still required, don't hesistate to open a separate issue.

**Comment by Creamers158** [comment]
It's nice to see how it resizes, love your work! I use Ginj still everyday all the day.
It's not always that I look for a history item. Usually when I want to recopy an item from the history, it's one of the recent captures but I also take captures "just in case I need it in the future" and those are found in the history, but when scrolling and searching for an item in history it's almost not doable. The capture has to be quite unique to recognize it. 
Because I rarely search in history (like twice a month)  I understand that it's probably too much work and/or too much code change to get this done. Hopefully there are other users requesting the same in the near future so it will be worth it.
Again, thanks for the updates. Have a nice Holiday!!
