### ISSUE TITLE
Saving a capture

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#17]
Request, 

When trying to save a file, it would be nicer is the File Name was already selected. Meaning, instead of selecting first.
I've also noticed that selecting everything and giving it a name, the extention is not used when saving.
In other words, a user needs to type a name and extention before saving.

Nicest would be that it is already selected and using the extention to save the file as shown in the Files of Type: PNG
![save](https://user-images.githubusercontent.com/6506666/88516237-403a9000-cfed-11ea-8e69-6681413682c8.png)

**Comment by vicnevicne** [comment]
I'm using a standard JFileChooser component, and the name should be highlighted by default, but it seems since I'm using a customized skin ("look and feel"), that behaviour gets lost - https://stackoverflow.com/questions/39916878/is-it-possible-to-select-the-file-name-in-a-jfilechooser-window
That will probably be hard to fix and will require digging deep into the internals of the component, so I'm not going to chase that issue right now.
On the other hand, adding the default extension if it is missing is ~~simple~~ done.

**Comment by vicnevicne** [comment]
Default extension is fixed in v0.3.7.
I'm afraid auto-selection will be a "won't fix" for now...

**Comment by Creamers158** [comment]
I'm happy with the fix. You can close if you want @vicnevicne

**Comment by vicnevicne** [comment]
OK thanks. And thanks for your help
