### ISSUE TITLE
Great, thanks. Can´t take screenshot from a 2nd display only main screen.

### ISSUE THREAD

**Issue by JuanZQ** [Ginj-capture/Ginj#2]
Great, thanks. Can´t take screenshot from a 2nd display only main screen.

**Comment by JuanZQ** [comment]
There is already an issue for multiscreen. Sorry guys. And thank you again for such a great tool (GINJ).

**Comment by vicnevicne** [comment]
Thanks for taking part in this experiment :-).
The first "issue" was more generic so I'm reopening this one focused on multiscreen and will post progress here.
Obviously that's the most wanted feature by 100.0% of the users :-)

**Comment by infinitebizmedia** [comment]
Great save on the app. very cool. just waiting for the multi-monitor update... ;)

**Comment by vicnevicne** [comment]
Should be fixed in version 0.3.3, just released. 
I tested with a weird configuration with a TV as secondary, but positioned on the left (so in negative coordinates) and it seems to work.
Note however that the "star" widget cannot be moved to secondary display yet. But capture should work on all displays and even across displays

![multiscreen1](https://user-images.githubusercontent.com/842233/87611333-1a1d1200-c708-11ea-8d5b-ca09a4471001.png)
![multiscreen2](https://user-images.githubusercontent.com/842233/87611337-1db09900-c708-11ea-9b30-abdd8f29d4f1.png)

Can you check it out and tell me what you think ? Thanks ! :-)

**Comment by JuanZQ** [comment]
Wow, that was fast. Thank you man.

**Comment by vicnevicne** [comment]
v0.3.4 adds the ability to also put the widget on a secondary screen and open windows there by default.

**Comment by janborup** [comment]
Hi @vicnevicne 

I have 3 monitors 
Monitor 1: 1920x1080 Scaling : 125%
Monitor 2: 1680x1050 Scaling : 100%
Monitor 3: 1680x1050 Scaling : 100%

Normal all monitor, look likes this:
![image](https://user-images.githubusercontent.com/6866443/87929113-33b2b680-ca86-11ea-9d95-cbbb47c2b4c6.png)

When i start Ginj capture, Ginj up-scaling all screens cracy, the bottom incl. taskbar dissapears, and the text look pixelated:
![image](https://user-images.githubusercontent.com/6866443/87929216-5ba21a00-ca86-11ea-92fe-f5a98046816d.png)

When I mark/drag a window, example the calculator on monitor 2, Ginj select something different:
![image](https://user-images.githubusercontent.com/6866443/87929581-f00c7c80-ca86-11ea-9c8d-00d6b5fca9b9.png)

The above screenshot is with Windows standard capture, that is working fine with the multible monitors.

Is this fixable ?

/Cheers

**Comment by janborup** [comment]
Hi @vicnevicne 
Would you take a look at above, is it fixable? 🥇 
Thanks

**Comment by vicnevicne** [comment]
@janborup : Sorry I missed your comments as this issue was closed.
Yes, zoom factor messes Ginj coordinates computation. I have no idea at all how Java receives this information. I'll have to investigate.
Could I ask you to open a separate issue on this topic and copy your report there as I believe it's not related to multi-display ? I've reopened this one in the meantime so it doesn't slip under the radar.
