### ISSUE TITLE
History - Reverse date

### ISSUE THREAD

**Issue by janborup** [Ginj-capture/Ginj#5]
Hi @vicnevicne 

A little small request.

Please sort history in Reverse date (Newest first)... in the Clip history... else when you have several clips, you always has to go to bottom for the newest clip.
![image](https://user-images.githubusercontent.com/6866443/87766508-8cc9e280-c819-11ea-9f02-c21d8074abf2.png)

/cheers

**Comment by vicnevicne** [comment]
You're right. Basically the whole sort & filter logic should be a 1-hour job, but I left it for later because of the specific look & feel they had in Jing... But I guess we can live with the current l&f and just make buttons work (and default to reverse date).
Btw, did you notice the improvement of history behaviour over Jing ? In Jing, history was basically a list of "flattened" bitmap versions of edited images. In Ginj, the unedited capture is saved, separately from a description of overlays, so re-opening a capture from history lets you remove or edit overlays :-)

**Comment by vicnevicne** [comment]
Default is "most recent first" now.

**Comment by vicnevicne** [comment]
History sort and filtering is implemented in v0.3.5 :-). I guess it can really be closed now.
