### ISSUE TITLE
Not an Issue - Just to say that I love GINJ and use it many times every day. It is the simplicity that makes it so useful.

### ISSUE THREAD

**Issue by DennisPolack** [Ginj-capture/Ginj#55]
Great Work. 
I Have purchased the Techsmith Snagit and Camtasia and have never used them. I only bought them because I liked Jing.

**Comment by DennisPolack** [comment]
It is the simplicity of GINJ that makes it so useful and a must to have.

**Comment by vicnevicne** [comment]
Thanks for your kind comment. I felt the same about Jing...

I hope you're not offended by me closing your new reports but I try to keep all related problems in a single issue :-) If you think the new ones are different, please tell me and I'll reopen them.
I'm really intrigued by your setup because I have no issue selecting handles, deleting selections or selecting a filename.
Let's try to nail these issues !

**Comment by DennisPolack** [comment]
Hi Vicne,

 

Thanks for the extremely rapid response.

 

No not offended at all – they are all trivial problems. 
I am surprised that no one else is having problems closing boxes. I have it quite often but discovered you can Just drag them out of the GINJ box.

See comments below

 

Wonderful app !

 

Best Wishes

Dennis
