### ISSUE TITLE
Feature request: Scrolling capture

### ISSUE THREAD

**Issue by desbest** [Ginj-capture/Ginj#58]
I have a feature request.
I would like a feature where I can do "scrolling capture" so Ginj can scroll down to the bottom of the page to then capture that.
It's useful for capturing really long web pages or pdf files.

And I want to be able to press the `Esc` key to then prematurely end the scrolling capture, to then have captured what has already been scrolled to, so far.

**Comment by vicnevicne** [comment]
Hi desbest,
Thanks for the suggestion.
Well, this is quite a complex feature because it requires interaction with the actual running windows, and Ginj being written in Java, it does not have OS-specific APIs.
However, for browser use, this can easily achieved without Ginj. It is even built-in in Firefox ("Options" Menu > "More tools" > "Customize Toolbar..." > Drag the "Screenshot" icon to Firefox's toolbar, then you can click on it and have the full page option) but is available through extensions for Chrome etc.
So I believe this feature will not be implemented in Ginj, at least not in the near future...
KR
