### ISSUE TITLE
Transparent background for text?

### ISSUE THREAD

**Issue by qu0zz** [Ginj-capture/Ginj#60]
I can't find a way to produce text with a transparent background. 
This would be useful because it's often the case that the opaque background behind the text obscures some part of the picture which is wanted. I don't know if the standard java colour-picker allows variable transparency?

(Noting that the following related comment will be in a separate issue/request: 
Also it's worth bearing in mind that the transparency also applies to the box surrounding the text. If the background is transparent you may not want a visible box around it, and it's not always visually appropriate to have a box surrounding a caption or text).

**Comment by vicnevicne** [comment]
Honestly making the background transparent is quite straightforward, but most of the work is creating a UI to choose to make it transparent or not.
Note that the original Jing had a floating menu above the annotation tool but it only allowed to change the font face, size and color (which could be different from the border), not the background. I didn't implement it because it was much work and I thought it wasn't absolutely required (and indeed nobody requested it here ;-)) but if we had it, that would be the perfect place...
As for the UI, do you think a simple "glass" icon would suffice or would a cursor be needed to select any level of transparency ? We could even go overboard and add a separate color picker to also allow selection of the background color, but I'd rather keep it simple, so either a toggle transparent/opaque white, or a cursor to adjust transparency. What do you think ?

**Comment by qu0zz** [comment]
hi vicnevicne
If given a choice the cursor would be my preferred option because it covers all bases, BUT I have to be honest, if a transparent background had been available I would have been very happy with that (and wouldn't have suggested variable transparency ) as I consider captioning being for "quick and dirty" annotation, so  it all depends on the amount of work you have to do to implement one or the other! (apologies for delay in reply).

**Comment by vicnevicne** [comment]
I had already worked on a "all or nothing" version in the meantime, so that's what is implemented in 0.4.12.
If you think a cursor for semi-transparency would be better, feel free to reopen it.
